/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-05-18 10:48:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h3>EDIT PROFILE</h3>\r\n");
      out.write("\r\n");
      out.write("\t<form class=\"form\" action=\"GetIdUserServlet\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" disabled class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"User Id\" name=\"Id\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(session.getAttribute("SLNo"));
      out.write("\">\r\n");
      out.write("\t\t\t\t<td class=\"td-actions text-right\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" class=\"form-control\" placeholder=\"User Id\"\r\n");
      out.write("\t\t\t\t\tname=\"Id\" value=\"");
      out.print(session.getAttribute("SLNo"));
      out.write("\">\r\n");
      out.write("\t\t\t\t<td class=\"td-actions text-right\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Full Name.\"\r\n");
      out.write("\t\t\t\t\tname=\"fullName\" value=\"");
      out.print(session.getAttribute("fullName"));
      out.write("\" />\r\n");
      out.write("\t\t\t\t<td class=\"td-actions text-right\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"Email\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tname=\"Email\" value=\"");
      out.print(session.getAttribute("Email"));
      out.write(" \" />\r\n");
      out.write("\t\t\t\t<td class=\"td-actions text-right\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"User Name\"\r\n");
      out.write("\t\t\t\t\tname=\"userName\" value=\"");
      out.print(session.getAttribute("userName"));
      out.write("\">\r\n");
      out.write("\t\t\t\t<td class=\"td-actions text-right\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"Password\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tname=\"password\" value=\"");
      out.print(session.getAttribute("password"));
      out.write("\" />\r\n");
      out.write("\t\t\t\t<td class=\"td-actions text-right\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"Role\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tname=\"Role\" value=\"");
      out.print(session.getAttribute("Role"));
      out.write("\" />\r\n");
      out.write("\t\t\t\t<td class=\"td-actions text-right\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"SLNo\" class=\"form-control\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(session.getAttribute("SLNo"));
      out.write(" \" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary btn-round\" type=\"submit\">Save\r\n");
      out.write("\t\t\t\tChanges</button>\r\n");
      out.write("\t\t\t<br> <br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<!--                                     <form> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("                                          <a href=\"#pablo\" class=\"btn btn-primary btn-round\">DELETE ACCOUNT</a> <br><br>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                      </form>    -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"DeleteCustomerAccountServlet\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"deleteValueAcc\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(session.getAttribute("cId"));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-primary btn-round\"\r\n");
      out.write("\t\t\t\tname=\"btnDelete\" value=\"submit\">DELETE ACCOUNT</button>\r\n");
      out.write("\t\t\t<br> <br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
